In [1]:
import numpy as np

In [2]:
def Solve(arr):
    empty_ind = firstEmptyIndex(arr)
    if empty_ind[0] == -1:
        print(arr)
        return True
    ints_opts = intsAllowedList(arr,empty_ind)
    if not ints_opts:
        return False
    for i in ints_opts:
        arr[empty_ind[0],empty_ind[1]] = i # try an option
        if Solve(arr):
            return True
        else:
            arr[empty_ind[0],empty_ind[1]] = 0

In [3]:
def firstEmptyIndex(arr):
    indexes = np.where(arr==0)
    if len(indexes[0]) > 0:
        return [indexes[0][0],indexes[1][0]]
    else:
        return [-1,-1]

In [4]:
def intsNotAllowedSet(arr,index):
    n , m = index
    row_set = set(arr[n,:])
    col_set = set(arr[:,m])
    block_set = set(arr[(3*(n//3)):(3*(n//3+1)),(3*(m//3)):(3*(m//3+1))].flatten())
    u = (row_set | col_set | block_set)
    u.discard(0)
    return u

In [5]:
def intsAllowedList(arr,index):
    not_allowed = intsNotAllowedSet(arr,index)
    allowed = {1, 2, 3, 4, 5, 6, 7, 8, 9}
    return sorted(allowed-not_allowed)

In [6]:
a = np.array([[0, 4, 3, 0, 8, 0, 2, 5, 0],
       [6, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 1, 0, 9, 4],
       [9, 0, 0, 0, 0, 4, 0, 7, 0],
       [0, 0, 0, 6, 0, 8, 0, 0, 0],
       [0, 1, 0, 2, 0, 0, 0, 0, 3],
       [8, 2, 0, 5, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 5],
       [0, 3, 4, 0, 9, 0, 7, 1, 0]])

In [7]:
print(a)

[[0 4 3 0 8 0 2 5 0]
 [6 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 1 0 9 4]
 [9 0 0 0 0 4 0 7 0]
 [0 0 0 6 0 8 0 0 0]
 [0 1 0 2 0 0 0 0 3]
 [8 2 0 5 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 5]
 [0 3 4 0 9 0 7 1 0]]


In [8]:
print(Solve(a))

[[1 4 3 9 8 6 2 5 7]
 [6 7 9 4 2 5 3 8 1]
 [2 8 5 7 3 1 6 9 4]
 [9 6 2 3 5 4 1 7 8]
 [3 5 7 6 1 8 9 4 2]
 [4 1 8 2 7 9 5 6 3]
 [8 2 1 5 6 7 4 3 9]
 [7 9 6 1 4 3 8 2 5]
 [5 3 4 8 9 2 7 1 6]]
True


In [9]:
b = np.array([[5, 3, 0, 0, 7, 0, 0, 0, 0],
       [6, 0, 0, 1, 9, 5, 0, 0, 0],
       [0, 9, 8, 0, 0, 0, 0, 6, 0],
       [8, 0, 0, 0, 6, 0, 0, 0, 3],
       [4, 0, 0, 8, 0, 3, 0, 0, 1],
       [7, 0, 0, 0, 2, 0, 0, 0, 6],
       [0, 6, 0, 0, 0, 0, 2, 8, 0],
       [0, 0, 0, 4, 1, 9, 0, 0, 5],
       [0, 0, 0, 0, 8, 0, 0, 7, 9]])
print(Solve(b))

[[5 3 4 6 7 8 9 1 2]
 [6 7 2 1 9 5 3 4 8]
 [1 9 8 3 4 2 5 6 7]
 [8 5 9 7 6 1 4 2 3]
 [4 2 6 8 5 3 7 9 1]
 [7 1 3 9 2 4 8 5 6]
 [9 6 1 5 3 7 2 8 4]
 [2 8 7 4 1 9 6 3 5]
 [3 4 5 2 8 6 1 7 9]]
True
